### PR TITLE
removing 1.1 api doc generation in ansible script

### PR DESCRIPTION
**Pull request by BillyAbildgaard**
@RackHD/veyron @michaelsteven

removing 1.1 apidoc generation from ansible script

### CODE REVIEW

**Comment by brianparry** [comment]
test this please

**Comment by michaelsteven** [comment]
I can confirm the ansible script does not break for me after this change, and apis are online.  Im not sure what else needs testing with the change other than swagger.

**Comment by BillyAbildgaard** [comment]
test this please

**Comment by BillyAbildgaard** [comment]
issues with the pipeline...
jenkins, test this please

**Pull request merged**
