### PR TITLE
ESXi install and 2.0 node discovery test updates

### PR DESCRIPTION
**Pull request by jlongever**
- Pass `acpi=off` for Platform-A ESXi install test
- Added 2.0 workflow API in 2.0 node discovery test group
- Fixed API 2.0 test order (incorrect dependent group name)

@brianparry @geoff-reid 

Jenkins: depends on https://github.com/RackHD/on-http/pull/491
Jenkins: depends on https://github.com/RackHD/on-tasks/pull/355

### CODE REVIEW

**Comment by anhou** [comment]
Jenkins: test this please.  For dependency build

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
nodes can't be discovered normally.
**vagrant.log**
http://10.240.19.21/job/Maglev-BRI-Test/job/on-multi/158/artifact/build/vagrant.log/*view*/
**smoke test  log**
http://10.240.19.21/job/Maglev-BRI-Test/job/smoke-test/490/console
Hope this could be helpful.


If the log shows it's not the code issue, I suggest to ignore the Jenkins-Dependency-PR result.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by amymullins** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Pull request merged**
