### PR TITLE
Update Redfish endpoint test group order

### PR DESCRIPTION
**Pull request by jlongever**

### CODE REVIEW

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by jlongever** [comment]
Resolves https://github.com/RackHD/RackHD/issues/450

**Comment by panpan0000** [comment]
:+0 .  if it fixes the redfish issues :-)

+ @changev

**Comment by uppalk1** [comment]
+1

**Comment by changev** [comment]
Error still exits in SH stack env

**Pull request merged**
