### PR TITLE
RAC-4348-rackhd_stack_init.py

### PR DESCRIPTION
**Pull request by gpaulos**
Recent changes in API 2.0 broke the passive switch and PDU discovery in stack init. This has not affected the PR gate since they don't have switches or PDUs, but did cause errors in MN smoke test. This PR updates these routines and also the following technical debt:

- change print statements to FIT logging
- clean up Hound violations

@hohene @larry-dean @jimturnquist @stuart-stanley @RackHD/corecommitters

### CODE REVIEW

**Comment by gpaulos** [comment]
test this please

**Comment by gpaulos** [comment]
Pre-checked style for no Hound violations. For some reason, automated Hound check is stalled.

**Comment by johren** [comment]
test this please

**Comment by gpaulos** [comment]
test this please

**Pull request merged**
