### PR TITLE
Fix isc-dhcp-server fail to start in 16.04 OVA

### PR DESCRIPTION
**Pull request by panpan0000**
because /etc/hostname is rackhd-demo (by scripts/dep.sh)

but in /etc/hosts, with install-command-line host=RackHD, it will be like
```
127.0.0.1 localhost
127.1.0.1 RackHD
```

so ```rackhd-demo``` can't be resolved.

### CODE REVIEW

**Comment by cgx027** [comment]
I would think ```rackhd-ova``` or ```rackhd-host``` may be a better name for both /etc/hostname and /etc/hosts. Using word ```demo``` as a name makes it looks like a more like a demo/dev env and stop our customers from using it in more formal env.

**Comment by cgx027** [comment]
+0 and non-blocking comment anyway.

**Comment by panpan0000** [comment]
HOLD ON MERGE!!!
I found some new problem..

**Comment by panpan0000** [comment]
create new https://github.com/RackHD/RackHD/pull/508 to replace this one.

**Pull request closed without merging**
