### PR TITLE
adding sudo for package install

### PR DESCRIPTION
**Pull request by heckj**
Thanks Jason (and sorry for the pain of missing this)

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by jlongever** [comment]
+1 test this please

**Comment by benbp** [comment]
👍

**Comment by anhou** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by jlongever** [comment]
Looks like this needs a rebase.

**Comment by heckj** [comment]
erp, yep - updating now

**Pull request merged**
