### PR TITLE
add start and stop command for footprint benchmark test

### PR DESCRIPTION
**Pull request by iceiilin**
Add independent start and stop commands for footprint benchmark tests, so that users can measure footprint about any operations they carry out. Modify some structure to adjust this changes.
@cgx027 @pengz1

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
test this please

**Comment by iceiilin** [comment]
test this please

**Comment by iceiilin** [comment]
test this please

**Comment by pengz1** [comment]
+1

**Comment by anhou** [comment]
:+1:

**Pull request merged**
