### PR TITLE
add the missing version for install-os sample payload

### PR DESCRIPTION
**Pull request by yyscamper**
The `version` is a required option for install-os which is defined in task-schema.

@RackHD/corecommitters @heckj @cgx027 @iceiilin @pengz1 @WangWinson

### CODE REVIEW

**Comment by changev** [comment]
test this please

**Comment by cgx027** [comment]
:+1:

**Comment by yyscamper** [comment]
@cgx027 : you concern is reasonable, I have updated the schema to let the minimum required length to be 1, see PR (https://github.com/RackHD/on-tasks/pull/327). So for this PR, I keep only changing the missing version option.

**Comment by brianparry** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by heckj** [comment]
👍

**Comment by cgx027** [comment]
:+1:

**Pull request merged**
