### PR TITLE
Fix: failed to apply obm settings

### PR DESCRIPTION
**Pull request by PengTian0**
Failed to get the catalog (source=bmc) when the graph "discovery" is not finished.
That caused the case failure: ```setup_ipmi_obm.setup_ipmi_obm```

@anhou @iceiilin @geoff-reid

### CODE REVIEW

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by anhou** [comment]
This PR also could resolve https://rackhd.atlassian.net/browse/RAC-5391

**Comment by PengTian0** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Pull request merged**
