### PR TITLE
Fix functional tests to work with new api 2.0 library version 1.0.2

### PR DESCRIPTION
**Pull request by geoff-reid**
Fixed the catalogs and config tests to work with the new api 2.0 library version 1.0.2.  This is a required fix before PR#160 can be merged.

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by brianparry** [comment]
:+1:

**Comment by dalebremner** [comment]
+1

**Pull request merged**
