### PR TITLE
modify benchmark cases to use common config.ini and workflow methods

### PR DESCRIPTION
**Pull request by iceiilin**
Update benchmark test cases to be accommodated with the latest code in test repo.

1. use rackhd ssh info in config.ini instead of environmental variables
2. use post_workflow method in workflows_tests.py and remove private functions in benchmark bootstrap class.

@jlongever @cgx027

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by iceiilin** [comment]
test this please

**Comment by iceiilin** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Pull request merged**
