### PR TITLE
Add fun tests for SerialInterfaces

### PR DESCRIPTION
**Pull request by srinia6**
Jenkins: depends on https://github.com/RackHD/on-http/pull/696

### CODE REVIEW

**Comment by srinia6** [comment]
Jenkins: depends on RackHD/on-http#696

**Comment by srinia6** [comment]
test this please

**Comment by srinia6** [comment]
Jenkins: Depends on https://github.com/RackHD/on-http/pull/696

**Comment by srinia6** [comment]
test this please

**Comment by changev** [comment]
Jenkins: depends on https://github.com/RackHD/on-http/pull/696

**Comment by geoff-reid** [comment]
Merging singe Jenkins and Unit tests passed at part of PR https://github.com/RackHD/on-http/pull/696

The dependency is not working for rackhd repo.

**Pull request merged**
