### PR TITLE
Add tests for /api/2.0/pollers route

### PR DESCRIPTION
**Pull request by brianparry**
Depends on https://github.com/RackHD/on-http/pull/173

### CODE REVIEW

**Comment by brianparry** [comment]
@RackHD/corecommitters @srinia6 @geoff-reid @abildw @dalebremner

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Comment by geoff-reid** [comment]
:+1:

**Pull request merged**
