### PR TITLE
fix packer build issue

### PR DESCRIPTION
**Pull request by keedya**
resolves  https://github.com/RackHD/RackHD/issues/407

@heckj @RackHD/corecommitters @jlongever @amymullins @zyoung51 @uppalk1 

here is a link to jenkins job with this fix:
http://rackhdci.lss.emc.com/job/vagrant-build/77/

### CODE REVIEW

**Comment by heckj** [comment]
nice Andre, thank you!

👍 

Worth nothing - change the PR description to say "resolves #407" to get this to resolve that issue when this is merged...

**Comment by jlongever** [comment]
Is the HTTP endpoint still necessary since authentication is enabled on the HTTPS endpoint?  Are both TLS/SSL and non-TLS/SSL endpoints needed?

Could the HTTPS be removed from config.json and firstuser.sh script? https://github.com/RackHD/RackHD/pull/415/files#diff-352352fdea3bd8f0c8601a2f1b1fbec0R6
https://github.com/RackHD/RackHD/blob/master/packer/ansible/roles/monorail/files/config.json#L12

**Comment by heckj** [comment]
I would be totally game for that - probably means we need to update the tutorial a bit, but we should head this direction to be sane and safe

**Comment by jlongever** [comment]
Agree-  having two authenticated endpoints seems redundant to me;  unless we want to demonstrate both encrypted and non-encrypted methods?

**Comment by amymullins** [comment]
@RackHD/corecommitters can you help with a review / merge? This PR will fix the broken packer build issue. 

@brianparry , can you help confirm a couple of @jlongever 's questions as this was enabled as part of the 2.0 API feature:
_Is the HTTP endpoint still necessary since authentication is enabled on the HTTPS endpoint? Are both TLS/SSL and non-TLS/SSL endpoints needed?_

**Comment by brianparry** [comment]
@jlongever We've been planning to get rid of the HTTP endpoint as part of the 1.1 API deprecation effort.  IMO, we should merge this PR as is and handle the endpoint stuff separately.

**Pull request merged**
