### PR TITLE
[Auth] Add httpEndpoints and auth fields

### PR DESCRIPTION
**Pull request by WangWinson**
Update config to support auth feature
- add 2 default endpoint for northbound/southbound API router
- add auth fields

@RackHD/corecommitters @cgx027 

Note: this PR should be merged together with https://github.com/RackHD/on-http/pull/93

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1: 
Please don't forget to update this file: https://github.com/RackHD/docs/blob/master/docs/rackhd/configuration.rst

**Comment by jlongever** [comment]
This will break the vagrant networking,  please update the VagrantFile to NAT the new port: https://github.com/RackHD/RackHD/blob/master/example/Vagrantfile#L24-L25

**Comment by WangWinson** [comment]
thanks @jlongever, I didn't aware of that. Will take look

**Comment by jlongever** [comment]
please test this

**Comment by anhou** [comment]
:+1:

**Comment by WangWinson** [comment]
@yyscamper  the `configuration.rst` update will come a little later together with API auth doc update

**Pull request merged**
