### PR TITLE
Validate Profile APIs

### PR DESCRIPTION
**Pull request by tannoa2**

### CODE REVIEW

**Comment by keedya** [comment]
@jlongever @benbp @uppalk1

**Comment by tannoa2** [comment]
@keedya

**Comment by keedya** [comment]
@RackHD/corecommitters

**Comment by heckj** [comment]
+1 - love the use of the swagger generated client in the tests.

**Comment by jlongever** [comment]
Cool.   We should make sure we run a valid profile end-to-end and don't limit the test to just checking the HTTP response.  +1

**Comment by jlongever** [comment]
I also realize some tests can be more simple, but tests like workflows and profiles become slightly more complex.

**Comment by keedya** [comment]
:+1:

**Pull request merged**
