### PR TITLE
Test instrumentation

### PR DESCRIPTION
**Pull request by manfrednde**
Testing wget

### CODE REVIEW

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
Test this please

**Comment by manfrednde** [comment]
Test this please

**Comment by johren** [comment]
This isn't showing me the download speed nor the download time.  I was hoping to see that it took XXX seconds and the speed was YYYY Mbps.

17:27:30 [manifest Install ESXI 6.0] 2017-06-23 17:27:30,233 INFO    +1.02 - STARTING TEST: [test02_get_files (test_api20_esxi_bootstrap.api20_bootstrap_esxi)] **** 
17:27:30 [manifest Install ESXI 6.0] 2017-06-23 17:27:30,235 INFO_5   Downloading upgrade.img file took:                                                        test.run 
17:27:30 [manifest Install ESXI 6.0] 2017-06-23 17:27:30 URL:http://10.240.19.193/repo/centos/7.0/images/pxeboot/upgrade.img [44035836/44035836] -> "upgrade.img" [1]
17:27:30 [manifest Install ESXI 6.0] 0.00user 0.16system 0:00.37elapsed 42%CPU (0avgtext+0avgdata 3288maxresident)k
17:27:30 [manifest Install ESXI 6.0] 0inputs+86008outputs (0major+181minor)pagefaults 0swaps
17:27:30 [manifest Install ESXI 6.0] .2017-06-23 17:27:30,622 INFO    -1.02 - ENDING TEST: [test02_get_files (test_api20_esxi_bootstrap.api20_bootstrap_esxi)]   ****

**Comment by johren** [comment]
Also, the IP address in the URL needs to be 172.31.128.1, not 10.240.19.193.

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by manfrednde** [comment]
test this please

**Comment by pathakvaidehi2391** [comment]
test this please

**Comment by pathakvaidehi2391** [comment]
test this please

**Comment by pathakvaidehi2391** [comment]
test this please

**Comment by pathakvaidehi2391** [comment]
test this please

**Comment by larry-dean** [comment]
test this please

**Comment by larry-dean** [comment]
test this please

**Comment by larry-dean** [comment]
test this please

**Comment by larry-dean** [comment]
test this please

**Comment by jimturnquist** [comment]
This PR was helping diagnosing CI/CD issues.  No merge necessary.  Closing.

**Pull request closed without merging**
