### PR TITLE
RAC-4105 Update Rack/test from pylint to flake8.

### PR DESCRIPTION
**Pull request by jimturnquist**
- create a .flake8 configuration file.  This contains exclusions
  that match the current state of our RackHD test code.  Further
  work will be necessary to better enforce coding standards.

- update mkcheck.sh to generate results in rackhd_test_check.txt

- added flake8 to requirements.txt

- deleted pylintrc

@johren @hohene @gpaulos @larry-dean

### CODE REVIEW

**Comment by johren** [comment]
Cool!  No violations found!

**Comment by johren** [comment]
Oh, looks like it was running hound before this?   So I assume the hound is not actually enabled yet since it doesn't have a .hound.yml file?

**Comment by jimturnquist** [comment]
@johren RackHD/RackHD needs houndci enabled here:

https://travis-ci.org/profile/RackHD

I don't have the power, do you?

**Comment by johren** [comment]
I'm wondering if we should push in a change that triggers a Hound violation just to make sure it is wired in correctly?

**Comment by jimturnquist** [comment]
@johren I'm not certain we are wired for hound as of yet.  I have a question out to Geoff this morning to get clarification.

**Comment by jimturnquist** [comment]
@johren I think we are there.  Ready for review / merge.

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by jimturnquist** [comment]
@larry-dean @hohene @gpaulos @derrickostertag 

Need a second +1 on this one.

**Comment by derrickostertag** [comment]
+1

**Pull request merged**
