### PR TITLE
Data Persistency in Docker Containers

### PR DESCRIPTION
**Pull request by ghost**
Changes designed to move data out of container volumes and intosubdirectories under ./docker/ .

Addressing issue #565.

### CODE REVIEW

**Comment by brianparry** [comment]
@rolandpoulter Would you mind taking a look at this?

**Comment by johren** [comment]
Pinging @rolandpoulter on this again.  Would you have a chance to look at this PR since you are most familiar with the docker compose files?

**Comment by PengTian0** [comment]
Can one of the admins verify this patch?

**Comment by miry** [comment]
@rolandpoulter @johren can you check again?

**Comment by lanchongyizu** [comment]
@miry could you resolve the conflict?

**Comment by RackHDCI** [comment]
The Copyright Check has failed!
The files listed below do not have a valid copyright statement:
- docker/dhcp/libdhcp/dhcp-leases - docker/elasticsearch/config/elasticsearch.yml - docker/elasticsearch/data/data/.keep - docker/elasticsearch/data/log/.keep - docker/mongo/db/.keep - docker/rabbitmq/log/.keep - docker/rabbitmq/mnesia/.keep

**Pull request closed without merging**
