### PR TITLE
Listen on AMQP for noop-example graph finish event.

### PR DESCRIPTION
**Pull request by tannoa2**
Fixes random workflow test failure.

@RackHD/corecommitters @zyoung51 @keedya @uppalk1

### CODE REVIEW

**Comment by heckj** [comment]
lgtm

**Comment by jlongever** [comment]
build timeout waiting for noop-example workflow to complete...2/3 nodes completed.
test this please

**Comment by jlongever** [comment]
@tannoa2 spoke with @benbp; seems this test is exposing the same random persistent status issue.  The on-taskgraph refactoring effort should resolve those types of behaviors.  Trying to reproduce with the Graph.Discovery test since that also checks the workflow status.

**Comment by jlongever** [comment]
@benbp this is really a non-issue if we're checking the status out of the AMQP message body right?

**Comment by jlongever** [comment]
+1

**Comment by jlongever** [comment]
@RackHD/corecommitters @keedya @uppalk1 @zyoung51 @tannoa2

**Comment by zyoung51** [comment]
+1

**Pull request merged**
