### PR TITLE
Functional test fix for PR 443

### PR DESCRIPTION
**Pull request by srinia6**
dependent on RackHD/on-http#443

Jenkins: depends on https://github.com/RackHD/on-http/pull/443

Fix for build failures on https://github.com/RackHD/on-http/pull/443 

@brianparry @BillyAbildgaard @dalebremner @keedya @geoff-reid @RackHD/corecommitters

### CODE REVIEW

**Comment by srinia6** [comment]
Jenkins: depends on https://github.com/RackHD/on-http/pull/443

**Comment by srinia6** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by srinia6** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
