### PR TITLE
Add data validation to catalogs funtcional tests

### PR DESCRIPTION
**Pull request by geoff-reid**
@RackHD/corecommitters @srinia6 @dalebremner @keedya @BillyAbildgaard @zyoung51

### CODE REVIEW

**Comment by brianparry** [comment]
:+1:

**Comment by amymullins** [comment]
@changev  or @panpan0000 , can you please help take a look?  github reporting Jenkins failure but Jenkins reporting the testing passed: http://rackhdci.lss.emc.com/job/RackHD/771/

**Comment by keedya** [comment]
:+1:

**Comment by yyscamper** [comment]
:+1:

**Comment by heckj** [comment]
@geoff-reid is the jenkins failure a real issue or something awry in the CI system at the moment? I know there's been trouble recently, but didn't want to merge this until it was clear it was OK

**Comment by geoff-reid** [comment]
test this please

**Comment by zyoung51** [comment]
+1

**Comment by geoff-reid** [comment]
The first Jenkins failure was just a CI system issue.  I could not even find a failed Jenkins job.  The re-run passed so it should be all set now.

**Pull request merged**
