### PR TITLE
bintray changed their download URIs, fixes #253

### LINKED ISSUE #253: ansible/rackhd_local.yml fails on downloading static image files
According to the "Ubuntu Source Based Installation", when I was running the step: "ansible-playbook -i "local," -K -c local rackhd_local.yml", the terminal outputs the wrong message,
"failed: [local] => (item=initrd.img-3.16.0-25-generic) => {"dest": "/root/src/on-http/static/http/common/initrd.img-3.16.0-25-generic", "failed": true, "item": "initrd.img-3.16.0-25-generic", "response": "Request failed: <urlopen error timed out>", "state": "absent", "status_code": -1, "url": "https://bintray.com/artifact/download/rackhd/binary/builds/initrd.img-3.16.0-25-generic"}
msg: Request failed
",
I use " ping https://bintray.com/artifact/download/rackhd/binary/builds/initrd.img-3.16.0-25-generic ",and I got " unknown host", so what should I do?

### PR DESCRIPTION
**Pull request by heckj**
bintray appears to have changed their download URI structures, so the base paths in Ansible need some tweaking to make this work.

@rolandpoulter do I need to make any relevant changes in the docker pieces to grab the relevant files from these new locations? If so, can you point me in the right direction.

FYI @StevenLee1

### CODE REVIEW

**Comment by heckj** [comment]
@RackHD/corecommitters please review

**Comment by benbp** [comment]
👍

**Comment by anhou** [comment]
@heckj  the docker's change location is  https://github.com/RackHD/RackHD/blob/master/docker/files/Dockerfile  need a batch replacement there :)

**Comment by anhou** [comment]
:+1: with docker's change

**Comment by heckj** [comment]
thanks @anhou will update

**Comment by heckj** [comment]
(not functioning yet, please don't merge)

**Comment by heckj** [comment]
I don't know what I did to determine this was broken, but when I double checked it with both `wget` and running ansible earlier today, the original code is fully funcitonal  - so closing this PR without merging it.

**Pull request closed without merging**
