### PR TITLE
Rename ipxe images to match on-dhcp-proxy bootfile name

### PR DESCRIPTION
**Pull request by jlongever**
Include EFI images

@RackHD/corecommitters @RackHD/rackhd_dev

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
could this be the root cause of your issues on discovery with our current example automation process? @heckj @benbp

**Comment by benbp** [comment]
:+1: seems likely @DavidjohnBlodgett

**Comment by heckj** [comment]
@benbp sorry, not likely because the ipxe bootloaders are checked into source control right now: (https://github.com/RackHD/on-tftp/tree/master/static/tftp)

**Comment by DavidjohnBlodgett** [comment]
I double checked @rolandpoulter 's environment and he found his /common dir to be empty. I have added sudo args to all ansible steps added for static files and we're seeing if this resolves any write permission issues.

**Comment by benbp** [comment]
If you ran with -vvv did you get any messages about why it wasn't copied? Should the run fail if it can't copy anyways?

**Comment by benbp** [comment]
Oh sorry @heckj I was ignorant of the PR context, I though @DavidjohnBlodgett was talking about discovery images.

**Pull request merged**
