### PR TITLE
Benchmark/add html pages

### PR DESCRIPTION
**Pull request by cgx027**
Add html files used to show footprint benchmark data. 

summary.html is the portal page. 

A follow PR will be filed for copying the html files into the report folder after test runs.

### CODE REVIEW

**Comment by cgx027** [comment]
@RackHD/corecommitters  @yyscamper @anhou @WangWinson @wuy1 @rolandpoulter

**Comment by cgx027** [comment]
test this please

**Comment by jlongever** [comment]
I think this web content belongs in it's own repository or maybe on-tools?  The test location is reserved for functional test content.

**Comment by heckj** [comment]
@jlongever has a good point - @cgx027 what's your thought/plan for how and where this information will be displayed? Can the presentation of the information be separated from the tests themselves so that we don't end up cluttering the benchmark test directories with presentation details?

**Comment by cgx027** [comment]
@jlongever @heckj , You guys have a good point. Those HTMLs are supposed to be copied to the output file where benchmark log data resides, so that it can take those log data and show to the users. I would agree on-tools seems like a better place. 

I will close this PR and create a new PR against on-tools to host those HTMLs.

**Comment by cgx027** [comment]
PR https://github.com/RackHD/on-tools/pull/22 created hence retire this PR.

**Pull request closed without merging**
