### PR TITLE
RAC-4182 - Staging the CIT redfish_1_0 test scripts into temp directory

### PR DESCRIPTION
**Pull request by hohene**
This PR is for ttaging the CIT redfish_1_0 test scripts into a temp directory for follow on PRs.
This will allow for doing diffs between original and converted scripts, without losing the master.
The scripts in this PR are a copy of the scripts in /test/tests/api/redfish_1_0 only, no updates,
They won't run as part of the CIT or FIT smoke tests in this form.

Plan is:
1. copy the original scripts into this staging area  (this PR)
2. mv the staged script and apply the converted script on top do show the diffs only for review
3. allow the converted script to run in FIT smoke suite.

For this PR. please ignore the hound errors.  This PR is copying existing scripts into a staging directory, and the hound errors will be fixed when we apply the NEW converted scripts.

### CODE REVIEW

**Comment by hohene** [comment]
test this please

**Comment by panpan0000** [comment]
test this please

**Comment by PengTian0** [comment]
test this please

**Comment by hohene** [comment]
test this please

**Comment by hohene** [comment]
@larry-dean @dalebremner @johren @jimturnquist @brianparry 
for my info:  http://rackhdci.lss.emc.com/job/RackHD/45/

**Comment by hohene** [comment]
@gpaulos @stuart-stanley

**Pull request merged**
