### PR TITLE
Fetch undionly.kpxe from ipxe

### PR DESCRIPTION
**Pull request by anhou**
related PR:
https://github.com/RackHD/on-imagebuilder/pull/32
https://github.com/RackHD/on-dhcp-proxy/pull/30

@RackHD/rackhd_dev @RackHD/corecommitters

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by stuart-stanley** [comment]
I guess I have the same question as JoeH over in the on-imagebuilder PR: what's the story on undionly.kpxe and undionly.kkpxe? I know we tripped over the two actually being different recently, but I still don't know *why* :)

**Comment by heckj** [comment]
fwiw: we learned empirically that the ESXi bootloaders will work with syslinux undionly.kkpxe, but not with the ipxe one. There's implications/conventions to the suffixes that are relevant. From http://forum.ipxe.org/showthread.php?tid=6989 (http://etherboot.org/wiki/gpxe_imagetypes):

- `.pxe` is an image designed to be chain loaded, unloading both the underlying PXE and UNDI code sections
- `.kpxe` is a PXE image that keeps UNDI loaded and unloads PXE
- `.kkpxe` is a PXE image that keeps PXE+UNDI loaded and return to PXE (instead of int 18h). From here

And there is also .kkkpxe - "The ipxelinux.0 build process should therefore now use undionly.kkkpxe instead of undionly.kkpxe."

Most often, you will want either .pxe, .kkpxe (for when you are using cached credentials, iirc), and .kkkpxe (usually the last two are in combination with pxelinux).

**Comment by stuart-stanley** [comment]
I don't even know what to think about ipxe's and syslinux's thought process in naming images with subtly different behaviors (and more importantly, the hidden application of those subtle differences!) with such, um, descriptive file names... kkkpxe? Egads. :)

More relevant, I think this means we should have at least the ones we have been known to use (kkpxe and kpxe) available in RackHD, so +1 from me.

Note: it would be nice to merge this before https://github.com/RackHD/on-imagebuilder/pull/31, so this can be sucked up into versioned packaging at the same time instead of later in an extra pass. Not required by any stretch of imagination, but it would shave an hour of boring work out of my personal schedule :)

**Comment by anhou** [comment]
Thanks @heckj  describing the difference of '.kpxe' '.kkpxe' '.kkkpxe'  , 
 @stuart-stanley and more, it will be crazy when we see both syslinux and ipxe have undionly.kpxe, but their behavior are different sometime. for example, from previous experience of debugging chainloading mboot.c32 when installing ESXi, even 'mboot.c32's boot options are same, syslinux succeed, but ipxe fail. it looks like they have different environment variables to boot mboot.c32 after some code hacking.  A little complex here, so agree with you that it should have the ones at least used by RackHD now.

**Comment by johren** [comment]
+1

**Comment by kostew** [comment]
Current docker images do not contain 'undionly.kpxe' which is required for a HW configuration under test in MN to work.  Would like to see this merged to unblock my test configuration.

**Comment by benbp** [comment]
@rolandpoulter see above comment from @kostew ^^

**Comment by benbp** [comment]
:+1:

**Pull request merged**
