### PR TITLE
RAC-5128 - Modify sel alert test to use fit

### PR DESCRIPTION
**Pull request by larry-dean**
* Modify to support new AMQP

### CODE REVIEW

**Comment by larry-dean** [comment]
@hohene @stuart-stanley @johren

**Comment by johren** [comment]
@larry-dean :  The Jenkins build passed, but there are some hound violations that need to be addressed.

**Comment by larry-dean** [comment]
test this please

**Comment by larry-dean** [comment]
Changes pushed for hound and PR requests

**Comment by larry-dean** [comment]
Added the required change from fit_common

**Pull request closed without merging**
