### PR TITLE
fix for static files not being written to common dir

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
quick fix for files not appearing in expected locations as seen in @rolandpoulter 's env.

### CODE REVIEW

**Comment by DavidjohnBlodgett** [comment]
@benbp

**Comment by benbp** [comment]
What are the permissions on that directory in the first place? Can't we just chmod it instead of having to use sudo?

**Comment by DavidjohnBlodgett** [comment]
vagrant@vagrant-ubuntu-trusty-64:~$ ls -all
total 48
drwxr-xr-x 6 vagrant vagrant 4096 Nov 16 23:52 .
drwxr-xr-x 4 root    root    4096 Nov 16 22:30 ..
-rw------- 1 vagrant vagrant  100 Nov 16 23:52 .bash_history
-rw-r--r-- 1 vagrant vagrant  220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 vagrant vagrant 3637 Apr  9  2014 .bashrc
drwx------ 2 vagrant vagrant 4096 Nov 16 22:30 .cache
-rw-r--r-- 1 root    root     176 Nov 16 22:57 .env
drwxr-xr-x 7 root    root    4096 Nov 16 22:51 n
-rw-r--r-- 1 root    root     640 Nov 16 22:57 Procfile
-rw-r--r-- 1 vagrant vagrant  675 Apr  9  2014 .profile
drwxrwxr-x 1 vagrant vagrant 4096 Nov 16 22:28 src
drwx------ 2 vagrant vagrant 4096 Nov 16 22:30 .ssh
vagrant@vagrant-ubuntu-trusty-64:~$


it looks like there should be no issue... but rolands system had nothing populating his common dir, and I got stuff to populate... to be honest at this time it's felt like ansible black magic... but I can continue to dig and try to provide a better answer

**Comment by DavidjohnBlodgett** [comment]
for better context all commands are run from the monorail server and files are placed in on-http through /src

**Comment by benbp** [comment]
Yeah I mean the directory permissions of the common directory, not `~`. Is is that common doesn't exist on his machine but does on yours?

**Comment by DavidjohnBlodgett** [comment]
so I checked the /common dir created by the sudo command issued in the below role and it seems to give open door permissions

https://github.com/RackHD/RackHD/blob/master/example/roles/repos/tasks/main.yml#L41

The only thing I can think of is maybe the host system could some how block the vagrant user trying to write to that directory because it does reside on the host... and by switching to root it tricks the host into allowing write access? that's a far stretch but maybe.

**Comment by DavidjohnBlodgett** [comment]
I could also add a mode flag to that step and try... depending on how deep down the rabbits whole we'd like to take it.

**Comment by benbp** [comment]
makes sense

**Comment by benbp** [comment]
@DavidjohnBlodgett yeah if you create the directory with `sudo: yes` then it's only going to be accessible by the root user.

**Comment by benbp** [comment]
Closing because it seems the problem is caused by the directory being created by the root user in the first place. Feel free to re-open if I'm mistaken.

**Pull request closed without merging**
