### PR TITLE
align coreos repo address with other OS

### PR DESCRIPTION
**Pull request by yyscamper**
@anhou @lanchongyizu @pengz1

### CODE REVIEW

**Comment by pengz1** [comment]
+1

**Comment by lanchongyizu** [comment]
:+1:  
@amymullins This PR might cause the OS install test failing in Jenkins. http://rackhdci.lss.emc.com/job/Continuous-Test/job/OS-Install-Jobs/job/CoreOS/

**Comment by yyscamper** [comment]
@amymullins @keedya : 

The purpose of this PR is just to align with all other OSes, in the sample of other OSes use the repo address "http://<server>:<port>/<osname>", but only CoreOS uses "http://<server>:<port>/repo/<osname>", the additional `repo` directly will cause user to pay special attention on CoreOS repo setup if user wants to directly use our sample payload.

I have examined the CIT test code, it always overwrite the repo address with what CIT setups, so I think there will be no impact on CIT, but I am not sure I have covered all aspects, please advise if there is something missing.

You could decide whether let this PR in, my opinion is to let in in the consideration of user friendly.

**Comment by amymullins** [comment]
@lanchongyizu and @yyscamper thanks for the heads up!  The PR is expected to pass given this value is overwritten by this line:  
https://github.com/RackHD/RackHD/blob/master/test/tests/api/v1_1/os_install_tests.py#L269
Should be no problem to merge this PR.

**Comment by keedya** [comment]
adding  @BillyAbildgaard

**Comment by keedya** [comment]
adding coreOS to Pr gate
test this please

**Comment by keedya** [comment]
test this please

**Comment by yyscamper** [comment]
Thanks @amymullins @keedya @BillyAbildgaard : When I design the progress notification for CoreOS, I also found the CoreOS installation wasn't stable, it often hung. I only tested in InfraSim, never try physical hardware, is that

**Comment by yyscamper** [comment]
@amymullins @keedya @BillyAbildgaard : thanks for you quick action and quick answer.

**Pull request merged**
