### PR TITLE
Add run os install on node per index

### PR DESCRIPTION
**Pull request by keedya**
@yyscamper I closed the other unintentionally .
Here is the response to your comments:

- Env variables are not shared between executors in jenkins
- I added sorting in the code to make sure I have consistency in node's order
- pipeline is not part of my task. Although i have a job running in sandbox using my branch to run all OSs in parallel
- I can send you a link to the  sandbox job offline

Adding @RackHD/corecommitters @geoff-reid @brianparry @hohene

### CODE REVIEW

**Comment by keedya** [comment]
Test this please

**Comment by keedya** [comment]
Comments addressed in the old PR :
https://github.com/RackHD/RackHD/pull/680

**Comment by yyscamper** [comment]
Base on the discussion on Slack channel, this PR is +1 after cleaning up the environment variable. The pipeline change can be moved to another story.

**Comment by keedya** [comment]
unrelated error
test this please

**Pull request merged**
