### PR TITLE
Add required fields to payload

### PR DESCRIPTION
**Pull request by dalebremner**
needed for:
https://github.com/RackHD/on-http/pull/579

### CODE REVIEW

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by keedya** [comment]
test this please

**Comment by brianparry** [comment]
test this please

**Pull request merged**
