### PR TITLE
remove 'current' from proxy config in CoreOS demo proxy setup

### PR DESCRIPTION
**Pull request by heckj**
- partial resolution for https://github.com/RackHD/RackHD/issues/146
 - to work with https://github.com/RackHD/on-http/pull/187

### CODE REVIEW

**Comment by heckj** [comment]
@RackHD/corecommitters reviews please

**Comment by yyscamper** [comment]
this PR is :+1: for me. I had a comment in the related PR (https://github.com/RackHD/on-http/pull/187), if we add the `version` parameter, it will be better to support CoreOS installation with different versions.

**Comment by anhou** [comment]
:+1:

**Comment by benbp** [comment]
Doesn't need a trailing slash?

**Comment by heckj** [comment]
Nope - verify that worked smoothly, and I start the url in the profile with `/`, so it's all covered, and matches the CoreOS expectation for the repo command.

**Comment by benbp** [comment]
:+1:

**Comment by yyscamper** [comment]
@benbp , the design of http-proxy will automatically add the trailing or leading slash if needs, eventually both `localPath` and `remotePath` will have trailing/leading slash or neither. See this code: https://github.com/RackHD/on-http/blob/master/lib%2Fservices%2Fhttp-service.js#L359-L374

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
