### PR TITLE
[redfish] Update http response code

### PR DESCRIPTION
**Pull request by zyoung51**

### CODE REVIEW

**Comment by zyoung51** [comment]
Depends on: https://github.com/RackHD/on-http/pull/478

**Comment by heckj** [comment]
👍

**Comment by anhou** [comment]
Jenkins: Depends on: https://github.com/RackHD/on-http/pull/478   and test this please
@zyoung51  confirmed with @changev need add 'Jenkins:' before 'depends on' to let dependency build work

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
@RackHD/corecommitters please review.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

**Comment by changev** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by changev** [comment]
test this please

sorry for that the Dependency-PR test suffered the error 
```
Test Name: redfish_emc_catalogs_test
Error Details: EMC Redfish Catalog size failure
```
This is a common error appear in other test too.
Except this error your PRs are ok.

I'm trying to test some more times see if it can pass this error.

**Comment by changev** [comment]
According to the test details your PRs are good.
I advice to do the merge just as before when no dependency-PR test, merge-one-test-another.
Till we fix the **EMC Redfish Catalog size failure**.

**Comment by yyscamper** [comment]
jenkins: test this please

**Comment by jlongever** [comment]
test this please

**Comment by rackhdmirror** [comment]
Build finished.

**Comment by jlongever** [comment]
+1

**Pull request merged**
