### PR TITLE
[skip ci]use newly build rackhd/files image instead of download directly

### PR DESCRIPTION
**Pull request by changev**
### Background

In docker build/docker compose up, used to build image ```rackhd/files```  with downloading static files from bintray directly, and this image don't be pushed to dockerhub.
As a result, rackhd docker images use static files without version control.
And this doesn't satisfy the needs of build/release.

### Details
This PR delete old docker rackhd/files image and edit docker-compose yml.

@panpan0000 @PengTian0 

### Related PRs

* add Dockerfile in on-imagebuilder repo https://github.com/RackHD/on-imagebuilder/pull/73
* modify ```docker_build.sh```script for on-imagebuilder docker build https://github.com/RackHD/on-build-config/pull/47

### CODE REVIEW

**Comment by panpan0000** [comment]
test this please

**Comment by panpan0000** [comment]
:+1:  since Jenkins already satisfied.

**Comment by PengTian0** [comment]
:+1:

**Comment by changev** [comment]
pleas don't merge

**Comment by rolandpoulter** [comment]
test this please

**Pull request merged**
