### PR TITLE
Add dhcpd.conf example to request profile without proxy.

### PR DESCRIPTION
**Pull request by jlongever**
Example to allow DHCP server to send bootfile request with mac/ip query.
Static host entry example
Handle option 93 arch type check

@RackHD/corecommitters @geoff-reid @keedya @zyoung51 @uppalk1 @tannoa2

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by benbp** [comment]
Do you think it's useful to remove a bunch of the commented out boilerplate config examples near the top?

:+1: regardless

**Comment by jlongever** [comment]
Yeah, probably.  It's all truncated from the /docs so probably not a big deal.

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by ytjohn** [comment]
:+1:

**Pull request merged**
