### PR TITLE
Update deploy/os_ova_install.py multiple VMs routine

### PR DESCRIPTION
**Pull request by gpaulos**
Fixed OVA installer for new FIT configuration system.
Multiple VM deployments now seed off of the 'ovamac' key in the stack config.

@hohene @jimturnquist @johren @larry-dean

### CODE REVIEW

**Comment by johren** [comment]
Please also remove the stack number check around line 114.  This is no longer necessary if we are not using that ID to compose the MAC.

**Comment by jimturnquist** [comment]
@johren Do you the line number correct in your comment above.

**Comment by johren** [comment]
Yep, just double-checked.  It checks to make sure the stack ID is a number if numvms > 1.  This is no longer necessary with George's change.

**Comment by gpaulos** [comment]
Removed number check for stack ID and tested as requested by @johren

**Pull request merged**
