### PR TITLE
update ucs tests to fix occasional failures

### PR DESCRIPTION
**Pull request by geoff-reid**
Several changes to UCS tests to improve reliability

1)  Move UCSPE initialization from state_init to main tests.
2)  If we cannot access UCSPE skip all UCS tests instead of failing
3)  UCSPE initialization will now wait for config to be valid

### CODE REVIEW

**Comment by PengTian0** [comment]
Thank you so much!
:+1:

**Comment by anhou** [comment]
@geoff-reid Just a confirmation, so this PR also could resolve https://rackhd.atlassian.net/browse/RAC-5378?

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Comment by geoff-reid** [comment]
test this please

**Pull request merged**
