### PR TITLE
Step forward submodules, packer rebuild

### PR DESCRIPTION
**Pull request by heckj**
Stepping forward the modules to rebuild a latest vagrant instance that leverages the most recent code.

resolves https://github.com/RackHD/RackHD/issues/96
believed will also resolve https://github.com/RackHD/RackHD/issues/94

### CODE REVIEW

**Comment by benbp** [comment]
Ah! :+1: 

FYI @DavidjohnBlodgett looks like I gave you an incomplete list of changes that needed to be made to support the config path update it seems?

**Comment by DavidjohnBlodgett** [comment]
oh dear, I thought I double checked what packer was using for the config name~ Sorry about that. :+1:

**Comment by DavidjohnBlodgett** [comment]
does this mean our on-core is broken? https://github.com/RackHD/on-core/blob/master/lib/common/constants.js#L46

**Comment by DavidjohnBlodgett** [comment]
@benbp ^^

**Comment by anhou** [comment]
:+1:

**Comment by anhou** [comment]
@DavidjohnBlodgett let me answer instead of @benbp  :-)  I think on-core is not broken, in my test yesterday, the old monorail.json will take effect, if no config.json, and if config.json exist, it will be used instead of monorail.json. it's just a problem of config.json for packer here.

**Pull request merged**
