### PR TITLE
removed sudo call when making common dir

### LINKED ISSUE #11: monorail_rack results don't discover the VM
@benbp @DavidjohnBlodgett  - updated details from a fresh run (as of 17nov AM)

I went through and cleaned out everything, resetting to run the instructions as per http://rackhd.readthedocs.org/en/latest/getting_started.html. The resulting system was functional, but the PXE.1 VM that the monorail_rack script created didn't get discovered.

VM PXE booted and got iPXE down, and then failed when requesting `/api/common/profiles`

screen shot 2015-11-17 at 12 07 35 pm

Is the service in this example running on port 8080? Is the iPXE script configured incorrectly for this setup?

In the logs, there's an HTTP 502 response to that URL request as well:

```
20:04:09 http.1   |  E 2015-11-17T20:04:09.634Z [on-http] [common-api-presenter] [Server] Lookup Record Not Found (findOneByTerm)
20:04:09 http.1   |   -> /lib/services/common-api-presenter.js:197
20:04:09 http.1   |  error:
20:04:09 http.1   |    message: Lookup Record Not Found (findOneByTerm)
20:04:09 http.1   |    name:    NotFoundError
20:04:09 http.1   |    context:
20:04:09 http.1   |      status: 404
20:04:09 http.1   |    status:  404
20:04:09 http.1   |  path:  /profiles
20:04:09 http.1   |  N 2015-11-17T20:04:09.650Z [on-http] [Services.ErrorPublisher] [Server] Event Loop Blocked
20:04:09 http.1   |   -> /node_modules/on-core/lib/services/error-publisher.js:93
20:04:09 http.1   |  host:     vagrant-ubuntu-trusty-64
20:04:09 http.1   |  name:     on-http
20:04:09 http.1   |  severity: notice
20:04:09 http.1   |  ms:       13
20:04:09 http.1   |  S 2015-11-17T20:04:09.653Z [on-http] [Http.Server] [Server] http: GET 404 18.502 - /api/common/profiles
20:04:09 http.1   |   -> /lib/services/http-service.js:113
20:04:09 http.1   |  ipAddress: 172.31.128.2
```

which makes me think we might be seeing a race condition on looking up the relevant IP address to be able to render out the correct "profiles" response.

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
This should fix any possible permissions issues with copying down the static files. 

resolves #11

### CODE REVIEW

**Comment by benbp** [comment]
Tested?

**Comment by DavidjohnBlodgett** [comment]
lol, you got me... stand by, I'm all over it.

**Comment by benbp** [comment]
"This should" tipped me off.

**Comment by DavidjohnBlodgett** [comment]
I'm honest to a fault ;)

**Comment by DavidjohnBlodgett** [comment]
ok, these last commits should fix all our pain points concerning the PXE race condition. @benbp @heckj

**Comment by DavidjohnBlodgett** [comment]
sorry omit "should" this has been tested

**Comment by heckj** [comment]
+1

**Comment by benbp** [comment]
:+1:

**Comment by benbp** [comment]
So FYI @keedya we found that whatever image is in on-tftp/static/tftp/monorail.ipxe does not have the same checksum as what's in bintray from on-imagebuilder, and the default image seems to not have your "sleeping" message in its default.ipxe script.

**Comment by keedya** [comment]
the one I built and commit to on-tftp is built with a different general.h file so i expect the checksum to be different. I m not sure what is built in on-imagebuilder but the monorail.ipxe i submitted in on-tftp includes my sleeping message(I already built an OVA with the changes and test it in our Lab)

**Comment by keedya** [comment]
@benbp  OVA build#66

**Comment by benbp** [comment]
Huh, ok thanks @keedya. @DavidjohnBlodgett so yeah not sure why we were having that problem then.

**Pull request merged**
