### PR TITLE
fix workflows 2.0 test dependencies

### PR DESCRIPTION
**Pull request by geoff-reid**
Fix dependencies in the 2.0 workflows tests.  Also change the mock data values so the 1.1 tests do not affect the 2.0 tests.  

This change will allow the 2.0 workflow tests to be successfully run independent of the 1.1 workflow tests.

### CODE REVIEW

**Comment by geoff-reid** [comment]
@abildw @dalebremner @srinia6 @brianparry

**Comment by abildw** [comment]
+1

**Comment by yyscamper** [comment]
:+1:

**Comment by dalebremner** [comment]
+1

**Pull request merged**
