### PR TITLE
making packer/ansible roles user home directory agnostic

### LINKED ISSUE #141: source install docs assume Vagrant
Reported by `dpasupathi` on Slack:

http://rackhd.readthedocs.org/en/latest/packaging_and_deployment.html#ubuntu-source-based-installation expects the home directory /home/vagrant to be installed and used as default. The docs need to be updated to accomodate this requirement, or the ansible roles need to be updated to deal with alternate home directories.

### PR DESCRIPTION
**Pull request by heckj**
# Packer updates

## Primary goals

- Updating ansible scripts to make them agnostic to home directory based on Ansible as opposed to using `/home/vagrant`. Resolves #141 
- Updating packer build process to build from latest versions of master, rather than the versions nailed in the submodules at https://github.com/rackhd/rackhd
- Adding a from-debian-package based VM creation tempalte

## Details
- collapsing `remoterepos` and `repos` roles so that if branch is specified as a variable to ansible, the submodules are updated to the on that branch (as opposed to pinned to where the submodule commits are currently nailed)
- added template-packages.json to build a RackHD VM image with debian packages from bintray
- added roles for package based installation
- updated image role to utilize facts now set in either packages or repo setup to identify static directories for `http` and `tftp` services in RackHD
- updated README for details on how to run (variables needed for ATLAS) and for how to run locally
- changed default values in post-processor to run from env variables
    (**NOTE**: **THIS BREAKS** the `packer push ...` as default build model, since a default packer
    build doesn't have the variables in remote builds. This can be remedied by adding the variables
    to the packer build, or (I think) added with the `-var` option when invoking `packer push`. 

`time packer build -only=virtualbox-iso template-packages.json` result:

```
real	25m29.101s
user	0m59.926s
sys	0m14.280s
```

`time packer build -only=virtualbox-iso template.json` result:

```
real	42m33.586s
user	1m45.877s
sys	0m15.310s
```

### CODE REVIEW

**Comment by heckj** [comment]
^^ resulting package build is v0.22 `heckj/rackhd` in vagrant if anyone wants to try it out

**Comment by heckj** [comment]
@RackHD/corecommitters reviews please

**Comment by anhou** [comment]
:+1:

**Comment by benbp** [comment]
:+1:

**Pull request merged**
