### PR TITLE
added on-http-api-2.0 to requirements.txt for tests

### PR DESCRIPTION
**Pull request by geoff-reid**
@dalebremner @brianparry @abildw @jlongever @srinia6

### CODE REVIEW

**Comment by geoff-reid** [comment]
removed the accidental commit of the updated submodules

**Comment by abildw** [comment]
:+1:

**Comment by dalebremner** [comment]
:+1: 
Thanks Geoff!!

**Comment by srinia6** [comment]
+1

**Comment by benbp** [comment]
:+1:

**Pull request merged**
