### PR TITLE
Add redfish and 2.0 API support

### PR DESCRIPTION
**Pull request by jlongever**
- Structure tests by API version
- Added Redfish 1.0 functional tests covering implemented APIs

@RackHD/corecommitters @tannoa2 @keedya @zyoung51 @uppalk1 @geoff-reid @dalebremner @srinia6 @abildw

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by benbp** [comment]
:+1: 

Dumb question, where is the on_http_redfish client coming from?

**Comment by jlongever** [comment]
@benbp the python library is generated in travis using swagger-codegen. It runs swagger-codegen against the YAML definition files (monorail-2.0.yaml, redfish.yaml) in the on-http repo and uploads debian packages to bintray.  I've also been manually uploading to my pypi account so they can be pip installed.  Not sure if it makes sense to create library repos under rackhd and check in the source?  Thoughts?

**Comment by jlongever** [comment]
test this please

**Comment by zyoung51** [comment]
+1

**Pull request merged**
