### PR TITLE
Add functional tests for authentication

### PR DESCRIPTION
**Pull request by keedya**
Add functional tests for authentication
- Create users
- modify users
- remove users
- Test Privileges

http://rackhd.readthedocs.io/en/latest/tutorials/vagrant.html needs to be modified. It will be tracked in a different story and PR

### CODE REVIEW

**Comment by keedya** [comment]
@RackHD/corecommitters @brianparry @dalebremner @srinia6 @BillyAbildgaard

**Comment by anhou** [comment]
:+1:

**Comment by keedya** [comment]
@RackHD/corecommitters

**Comment by brianparry** [comment]
:+1:

**Pull request merged**
