### PR TITLE
remove duplicated minLogLevel & change minLogLevel to 0

### PR DESCRIPTION
**Pull request by yyscamper**
Change includes:
(1) Remove the duplicated minLogLevel
(2) Change minLogLevel to 0, so that the debug message can also be printed. This will help to identify issue in Jenkin CI (The Jenkins uses this config in testing) and customer reported bugs.

@heckj @RackHD/corecommitters @jlongever   @panpan0000 @PengTian0 @changev

### CODE REVIEW

**Comment by panpan0000** [comment]
good catch to remove the duplicated loglevel definiton.

if the loglevel 0 will not bring system slow down ,and the burst of debug message does helpful to developers ( including external users who use Vagrant releases ), then fine to me .

**Comment by yyscamper** [comment]
Jenkins: test this please

**Comment by benbp** [comment]
👍

**Comment by heckj** [comment]
I'd prefer to leave the minLogLevel in the default configuration to 3 (info level), simply because I think it would be a better experience for people trying out RackHD with Vagrant to not get all the additional detail, which is prominently displayed based on how we run the example setup from source.

I totally agree we should reset this as needed for instances like Jenkins where we could use the additional debugging. I *think* it would be easier to make the one-time change needed for jenkins, or developers can make the change manually in their own local systems if they want to see increased debugging.

Alternatively, we can make the public Vagrant instance of RackHD with an alternate file that has the decreased debugging logging.

@panpan0000 how are you using vagrant in your CI setup? Are you pulling directly from rackhd/rackhd vagrant image and using that directly? Are you building your own locally?

**Comment by PengTian0** [comment]
test this please

**Comment by panpan0000** [comment]
@heckj  , you are right. 
it should use a customized config.json , there does have one, but never take effect.
I made an PR as below:
https://github.com/RackHD/on-build-config/pull/19

But Felix's PR still valid to remove duplicated twice Log-level definition :-) 

@yyscamper , can you rework your PR?

**Comment by yyscamper** [comment]
@panpan0000 , @heckj : I will keep the previous information log level

**Comment by yyscamper** [comment]
@panpan0000 @heckj : done!

**Comment by PengTian0** [comment]
test this please

**Comment by anhou** [comment]
:+1:

**Comment by cgx027** [comment]
:+1:

**Pull request merged**
