### PR TITLE
[redfish] Add EventService Functional Tests

### PR DESCRIPTION
**Pull request by jlongever**
Added Redfish event service functional tests
Added simple httpd server to test webhook functionality of event services
Added continuous run option to worker class
Added timeout assertion for worker task

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya @geoff-reid

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by anhou** [comment]
test this please

**Comment by tannoa2** [comment]
+1

**Comment by benbp** [comment]
👍

**Pull request merged**
