### PR TITLE
Add AMQP listener mode utility

### PR DESCRIPTION
**Pull request by jlongever**
Pass --amqp option with exchange/queue parameters to listen continuously on exchange

Optional tool.  Take it or leave it.

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @geoff-reid @keedya

### CODE REVIEW

**Comment by tannoa2** [comment]
test this please

**Comment by zyoung51** [comment]
Should optional utilities/tools be in the on-tools repo?  +1 from me either way.

**Comment by jlongever** [comment]
@zyoung51 probably, but since it reuses classes defined in test I just made it an option.

**Comment by benbp** [comment]
@jlongever yeah we have a similar utility at https://github.com/RackHD/on-tools/blob/master/dev_tools/sniff.js, though there seems to be a bit more functionality here. Might be worth a README mention if you're going to add this?

👍

**Comment by iceiilin** [comment]
+1 This tool will be useful

**Comment by heckj** [comment]
👍 looks great, thinking maybe we should kill the tooling in on-tools/dev_tools/sniff.js - especially where this could be leveraged to get better insight into the system for testing, which I suspect is some of the desire/drive here (at least that's my guess based on it being in `tests` - was that part of the intent @jlongever ?)

**Comment by jlongever** [comment]
@heckj tbh I didn't put too much thought into it,  this was something I used while testing out new poller alerts and figured it would be useful under the integration test framework.  Same with the  `--httpd` option as well,  was used for validating Redfish EventService webhook functionality.

**Pull request merged**
