### PR TITLE
test README.md cleanup

### PR DESCRIPTION
**Pull request by jlongever**
Add on-http pypi to pip requirements file, remove apt-get dependency.
Fix BMC credentials prompt

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @tldavies

### CODE REVIEW

**Comment by jlongever** [comment]
^^ known test error

**Comment by jlongever** [comment]
test this please

**Comment by yyscamper** [comment]
:+1:

**Comment by keedya** [comment]
:+1:

**Pull request merged**
