### PR TITLE
Rac 249 Vagrant installer

### PR DESCRIPTION
**Pull request by gpaulos**
This PR contains a new 'Vagrant' RackHD installer for workstation-based development and test environments.

This update consists of two files:
test/fit_tests/Vagrantfile
test/fit_tests/README.md

Vagrantfile is a script that executes the following procedures:
- downloads and starts a Ubuntu 16 template from Vagrant Atlas as server
- runs the FIT source installer to load the latest RackHD on Ubuntu server
- configures RackHD to run on the Vagrant host
- starts up RackHD
- loads SKU packs
- downloads and starts InfraSim Quanta D51 simulator

The README.md file has detailed instructions on how to configure and run the script.

This PR is dependent upon the following PRs to run properly:
https://github.com/RackHD/RackHD/pull/491
https://github.com/RackHD/RackHD/pull/487

This has been tested using Windows 7 and Ubuntu 16 desktop environments.

The 'template' section of the Vagrantfile is for future use in Jenkins automation.

### CODE REVIEW

**Comment by brianparry** [comment]
@keedya Would you mind taking a look at this?

**Comment by keedya** [comment]
Looks good :+1:

**Comment by cgx027** [comment]
Looks good. :+1:

**Comment by gpaulos** [comment]
@RackHD/corecommittersanhou, benbp, brianparry, tldavies, and yyscamper please review.

**Comment by gpaulos** [comment]
@RackHD/corecommitters please review

**Pull request merged**
