### PR TITLE
revise esxi full payload

### PR DESCRIPTION
**Pull request by lanchongyizu**
* add ntpServers
* support MAC address for device included in networkDevices
* support MAC address for uplinks included in switchDevices

### CODE REVIEW

**Comment by yyscamper** [comment]
:+1:

**Comment by yyscamper** [comment]
@RackHD/corecommitters @zyoung51

**Comment by lanchongyizu** [comment]
@panpan0000

**Comment by iceiilin** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Pull request merged**
