### PR TITLE
Filter logs

### PR DESCRIPTION
**Pull request by heckj**
adding default filtering to "notice" level to calm down the demonstration log output

### CODE REVIEW

**Comment by heckj** [comment]
@benbp @dalebremner @brianparry adding filtering to the demo setup - will make a corresponding PR to take the low-level notices about blocking the event loop from notice to debug in on-core

**Comment by benbp** [comment]
info level perhaps better in light of https://github.com/RackHD/RackHD/issues/34 ?

**Comment by heckj** [comment]
yeah, thinking so - when we merge in any log level changes, I'll swing back by and update this

**Comment by benbp** [comment]
:+1:

**Pull request merged**
