### PR TITLE
Add and setup PostgreSQL backend services

### PR DESCRIPTION
**Pull request by jlongever**
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

### CODE REVIEW

**Comment by heckj** [comment]
did you want to always add postgres to the image, or choose between postgres and mongo?

**Comment by jlongever** [comment]
Always - at least temporarily since the current workflow related stores are tied to mongo so the initial postgres PR will exclude them.  That support will come later after some additional refactoring around the workflow related store.  

@benbp @zyoung51 correct me if I'm wrong here.

**Comment by jlongever** [comment]
@heckj fyi,  @zyoung51 added backend DB override options to the config:
https://github.com/RackHD/on-build-config/pull/9/files#diff-c6eccdca1e61b2dd0a6da07d0b0b8d67R65

So there could actually be mixed databases supported here,  at least in the short term.

**Comment by heckj** [comment]
ah, cool - missed that :+1: 

Could we also get documentation added to the docs describing the databaseOvereide config structure and how to use it please?

**Comment by jlongever** [comment]
@zyoung51 is still working on getting the PR up (I'm a little ahead of him ;)) but the docs will definitely get updated once its in.

**Comment by heckj** [comment]
ah! :+1: code/PR race is on, eh?

**Comment by jlongever** [comment]
In @zyoung51's defense his PR is a little more involved.

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
