### PR TITLE
RAC-5040 CentOS 6.5 FIT OS Install

### PR DESCRIPTION
**Pull request by gpaulos**
This is the PR gate CenntOS 6.5 FIT OS install test.

This PR is a prerequisite to the main PR from on-build-config.

This PR only includes a payload file and an increase in the OS install timeout.

@johren @hohene

### CODE REVIEW

**Comment by gpaulos** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Comment by johren** [comment]
test this please

**Pull request merged**
