### PR TITLE
updating ansible playbook for node4

### PR DESCRIPTION
**Pull request by heckj**
- no longer install legacy (node 0.10) packages
 - install nodesource node4 packages
- removing ansible role for node 0.10

### CODE REVIEW

**Comment by heckj** [comment]
@panpan0000 @RackHD/corecommitters please review

**Comment by DavidjohnBlodgett** [comment]
@heckj would this require a fix for our Procfile to kick off the correct binary?

**Comment by heckj** [comment]
@DavidjohnBlodgett nope - this is just for package installs to not bother installing the legacy ubuntu nodejs debian packages, and bringing this ansible playbook up to date with the other node4 based pieces that are already in place.

**Comment by anhou** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
👍

**Pull request merged**
