### PR TITLE
Added tests for the WORKFLOWTASKS and the WORKFLOWS

### PR DESCRIPTION
**Pull request by tannoa2**
@RackHD/corecommitters @zyoung51 @keedya @uppalk1

### CODE REVIEW

**Comment by jlongever** [comment]
@tannoa2 These all just verify the HTTP responses,  we should also be validating the workflow/task execution.   Even if it's a simple no-op workflow test it's better than nothing.

**Comment by tannoa2** [comment]
OK, I will add it

**Comment by jlongever** [comment]
UNSTABLE -

**Comment by jlongever** [comment]
+1

**Comment by keedya** [comment]
:+1:

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
@tannoa2 could you check on the merge conflicts?

**Comment by tannoa2** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
@tannoa2 that should be a real failure,  could you check it out?

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
+1

**Pull request merged**
