### PR TITLE
removed all refs to OnRack

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
@heckj @benbp 

Please do not merge, this is blocked...

### CODE REVIEW

**Comment by jlongever** [comment]
test this please

**Comment by jlongever** [comment]
+1
@DavidjohnBlodgett could you rebase?

**Comment by DavidjohnBlodgett** [comment]
@jlongever understood, I'll rebase ASAP... in addition this is blocked by https://github.com/RackHD/on-core/pull/69

**Comment by DavidjohnBlodgett** [comment]
@jlongever rebase completed.

**Comment by jlongever** [comment]
test this please

**Comment by DavidjohnBlodgett** [comment]
@benbp @jlongever this is now unblocked.

**Comment by jlongever** [comment]
crap,  was missing a +1.   merged anyways.

**Pull request merged**
